version: '3.8'

services:
  streamlit:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    environment:
      - PYTHONPATH=/app
    restart: unless-stopped
    networks:
      - streamlit-network

networks:
  streamlit-network:
    driver: bridge